// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20251114021340_FixTableStructure18")]
    partial class FixTableStructure18
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjectCycleManage.Model.AnnualBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Budget")
                        .HasColumnType("int")
                        .HasComment("预算");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnnualBudgetTable", t =>
                        {
                            t.HasComment("年度预算");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.EquipTypeStageDocTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectStageId")
                        .HasColumnType("int")
                        .HasComment("阶段-例-项目评审");

                    b.Property<int>("documenttypeId")
                        .HasColumnType("int")
                        .HasComment("文档-例-设备名称");

                    b.Property<int?>("equipmenttypeId")
                        .HasColumnType("int")
                        .HasComment("设备类型");

                    b.HasKey("Id");

                    b.HasIndex("ProjectStageId");

                    b.HasIndex("documenttypeId");

                    b.HasIndex("equipmenttypeId");

                    b.ToTable("EquipTypeStageDocTable", t =>
                        {
                            t.HasComment("设备类型-阶段-文档对应表");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.EquipTypeStageInfoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InformationId")
                        .HasColumnType("int")
                        .HasComment("信息-例-设备名称");

                    b.Property<int>("ProjectStageId")
                        .HasColumnType("int")
                        .HasComment("阶段-例-项目评审");

                    b.Property<int?>("equipmenttypeId")
                        .HasColumnType("int")
                        .HasComment("设备类型");

                    b.HasKey("Id");

                    b.HasIndex("InformationId");

                    b.HasIndex("ProjectStageId");

                    b.HasIndex("equipmenttypeId");

                    b.ToTable("EquipTypeStageInfoTable", t =>
                        {
                            t.HasComment("设备类型-阶段-信息对应表");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.FileTypesTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileTypesName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FileTypesTable", t =>
                        {
                            t.HasComment("文件类型");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.InformationTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Infor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("InforTypesDataId")
                        .HasColumnType("int")
                        .HasComment("信息类型-例-信息-时间");

                    b.Property<string>("Permission")
                        .HasColumnType("longtext")
                        .HasComment("权限分级");

                    b.Property<string>("Reamrks")
                        .HasColumnType("longtext")
                        .HasComment("备注");

                    b.HasKey("Id");

                    b.HasIndex("InforTypesDataId");

                    b.ToTable("InformationTable", t =>
                        {
                            t.HasComment("信息表");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.PermInfoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Perm")
                        .HasColumnType("int")
                        .HasComment("权限等级");

                    b.Property<string>("PermName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("权限名称-例-跟进人");

                    b.HasKey("Id");

                    b.ToTable("PermInfoTable", t =>
                        {
                            t.HasComment("权限信息表");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.ProjFlowTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProjFlowInfor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("流程信息-例-项目评审");

                    b.HasKey("Id");

                    b.ToTable("ProjFlowTable", t =>
                        {
                            t.HasComment("项目流程表");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.TypeApprFlowPersSeqTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mark")
                        .HasColumnType("longtext")
                        .HasComment("标记-Dele表示删除");

                    b.Property<int?>("ReviewerPeopleId")
                        .HasColumnType("int")
                        .HasComment("审核人员");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int")
                        .HasComment("顺序");

                    b.Property<int?>("equipmenttypeId")
                        .HasColumnType("int")
                        .HasComment("设备类型");

                    b.Property<int?>("projectflowId")
                        .HasColumnType("int")
                        .HasComment("流程信息");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerPeopleId");

                    b.HasIndex("equipmenttypeId");

                    b.HasIndex("projectflowId");

                    b.ToTable("TypeApprFlowPersSeqTable", t =>
                        {
                            t.HasComment("类型审批流程人员顺序表");
                        });
                });

            modelBuilder.Entity("ProjectManagement.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FileTypesDataId")
                        .HasColumnType("int")
                        .HasComment("文档类型-例-文档-OA");

                    b.Property<string>("Permission")
                        .HasColumnType("longtext")
                        .HasComment("权限分级");

                    b.HasKey("DocumentTypeId");

                    b.HasIndex("FileTypesDataId");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("ProjectManagement.Models.EquipmentType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipmentTypeId"));

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EquipmentTypeId");

                    b.ToTable("EquipmentType", t =>
                        {
                            t.HasComment("设备类型-例：非标外购");
                        });
                });

            modelBuilder.Entity("ProjectManagement.Models.InspectionRecord", b =>
                {
                    b.Property<int>("InspectionRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InspectionRecordId"));

                    b.Property<string>("CheckOpinion")
                        .HasColumnType("longtext");

                    b.Property<int?>("CheckPeopleId")
                        .HasColumnType("int");

                    b.Property<string>("CheckResult")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CheckTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int")
                        .HasComment("顺序");

                    b.Property<int>("projId")
                        .HasColumnType("int")
                        .HasComment("流程ID记录");

                    b.HasKey("InspectionRecordId");

                    b.HasIndex("CheckPeopleId");

                    b.HasIndex("ProjectsId");

                    b.HasIndex("projId");

                    b.ToTable("InspectionRecord");
                });

            modelBuilder.Entity("ProjectManagement.Models.PeopleTable", b =>
                {
                    b.Property<int>("PeopleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeopleId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PeopleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Permission")
                        .HasColumnType("longtext")
                        .HasComment("权限信息");

                    b.HasKey("PeopleId");

                    b.ToTable("PeopleTable");
                });

            modelBuilder.Entity("ProjectManagement.Models.ProjectDocumentStatus", b =>
                {
                    b.Property<int>("ProjectDocumentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectDocumentStatusId"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsHasDocument")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TheLastUpDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatePeopleId")
                        .HasColumnType("int");

                    b.HasKey("ProjectDocumentStatusId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ProjectsId");

                    b.HasIndex("UpdatePeopleId");

                    b.ToTable("ProjectDocumentStatus");
                });

            modelBuilder.Entity("ProjectManagement.Models.ProjectPhaseStatus", b =>
                {
                    b.Property<int>("ProjectPhaseStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectPhaseStatusId"));

                    b.Property<string>("ProjectPhaseStatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectPhaseStatusId");

                    b.ToTable("ProjectPhaseStatus", t =>
                        {
                            t.HasComment("项目阶段状态表，例-进行中/已完结");
                        });
                });

            modelBuilder.Entity("ProjectManagement.Models.ProjectStage", b =>
                {
                    b.Property<int>("ProjectStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectStageId"));

                    b.Property<string>("ProjectStageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectStageId");

                    b.ToTable("ProjectStage", t =>
                        {
                            t.HasComment("项目阶段表，例-项目评审/设备采购");
                        });
                });

            modelBuilder.Entity("ProjectManagement.Models.ProjectTypeDocumentAssociationTable", b =>
                {
                    b.Property<int>("ProjectTypeDocumentAssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectTypeDocumentAssociationId"));

                    b.Property<int?>("DisplaySequence")
                        .HasColumnType("int");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsNecessary")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ProjectTypeDocumentAssociationId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("ProjectTypeDocumentAssociationTables");
                });

            modelBuilder.Entity("ProjectManagement.Models.Projects", b =>
                {
                    b.Property<int>("ProjectsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectsId"));

                    b.Property<string>("ActualExpenditure")
                        .HasColumnType("longtext");

                    b.Property<string>("Applicant")
                        .HasColumnType("longtext")
                        .HasComment("申请人");

                    b.Property<DateTime?>("ApplicationTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("申请时间");

                    b.Property<string>("AssetNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Budget")
                        .HasColumnType("longtext");

                    b.Property<int?>("DaysDiff")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentName")
                        .HasColumnType("longtext");

                    b.Property<int?>("FileProgress")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSubmitTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("最后一次提交审核时间");

                    b.Property<string>("ProcurementMonth")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProjInforId")
                        .HasColumnType("int")
                        .HasComment("流程ID");

                    b.Property<int?>("ProjectCycle")
                        .HasColumnType("int")
                        .HasComment("项目周期");

                    b.Property<string>("ProjectIdentifyingNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProjectLeaderId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProjectPhaseStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectProgress")
                        .HasColumnType("int");

                    b.Property<int>("ProjectStageId")
                        .HasColumnType("int");

                    b.Property<string>("UsingDepartment")
                        .HasColumnType("longtext")
                        .HasComment("使用部门");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.Property<int?>("equipmenttypeId")
                        .HasColumnType("int");

                    b.Property<int?>("projectfollowuppersonId")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .HasColumnType("longtext");

                    b.Property<int?>("typeId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsId");

                    b.HasIndex("ProjInforId");

                    b.HasIndex("ProjectLeaderId");

                    b.HasIndex("ProjectPhaseStatusId");

                    b.HasIndex("ProjectStageId");

                    b.HasIndex("equipmenttypeId");

                    b.HasIndex("projectfollowuppersonId");

                    b.HasIndex("typeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectManagement.Models.TypeTable", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TypeId");

                    b.ToTable("TypeTable", t =>
                        {
                            t.HasComment("项目类型表，例：复制/新增/改善");
                        });
                });

            modelBuilder.Entity("ProjectCycleManage.Model.EquipTypeStageDocTable", b =>
                {
                    b.HasOne("ProjectManagement.Models.ProjectStage", "ProjectStage")
                        .WithMany()
                        .HasForeignKey("ProjectStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.DocumentType", "documenttype")
                        .WithMany()
                        .HasForeignKey("documenttypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.EquipmentType", "equipmenttype")
                        .WithMany()
                        .HasForeignKey("equipmenttypeId");

                    b.Navigation("ProjectStage");

                    b.Navigation("documenttype");

                    b.Navigation("equipmenttype");
                });

            modelBuilder.Entity("ProjectCycleManage.Model.EquipTypeStageInfoTable", b =>
                {
                    b.HasOne("ProjectCycleManage.Model.InformationTable", "Information")
                        .WithMany()
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.ProjectStage", "ProjectStage")
                        .WithMany()
                        .HasForeignKey("ProjectStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.EquipmentType", "equipmenttype")
                        .WithMany()
                        .HasForeignKey("equipmenttypeId");

                    b.Navigation("Information");

                    b.Navigation("ProjectStage");

                    b.Navigation("equipmenttype");
                });

            modelBuilder.Entity("ProjectCycleManage.Model.InformationTable", b =>
                {
                    b.HasOne("ProjectCycleManage.Model.FileTypesTable", "InforTypesData")
                        .WithMany()
                        .HasForeignKey("InforTypesDataId");

                    b.Navigation("InforTypesData");
                });

            modelBuilder.Entity("ProjectCycleManage.Model.TypeApprFlowPersSeqTable", b =>
                {
                    b.HasOne("ProjectManagement.Models.PeopleTable", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerPeopleId");

                    b.HasOne("ProjectManagement.Models.EquipmentType", "equipmenttype")
                        .WithMany()
                        .HasForeignKey("equipmenttypeId");

                    b.HasOne("ProjectCycleManage.Model.ProjFlowTable", "projectflow")
                        .WithMany()
                        .HasForeignKey("projectflowId");

                    b.Navigation("Reviewer");

                    b.Navigation("equipmenttype");

                    b.Navigation("projectflow");
                });

            modelBuilder.Entity("ProjectManagement.Models.DocumentType", b =>
                {
                    b.HasOne("ProjectCycleManage.Model.FileTypesTable", "FileTypesData")
                        .WithMany()
                        .HasForeignKey("FileTypesDataId");

                    b.Navigation("FileTypesData");
                });

            modelBuilder.Entity("ProjectManagement.Models.InspectionRecord", b =>
                {
                    b.HasOne("ProjectManagement.Models.PeopleTable", "CheckPeople")
                        .WithMany()
                        .HasForeignKey("CheckPeopleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectManagement.Models.Projects", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectCycleManage.Model.ProjFlowTable", "proj")
                        .WithMany()
                        .HasForeignKey("projId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckPeople");

                    b.Navigation("Projects");

                    b.Navigation("proj");
                });

            modelBuilder.Entity("ProjectManagement.Models.ProjectDocumentStatus", b =>
                {
                    b.HasOne("ProjectManagement.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.Projects", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.PeopleTable", "UpdatePeople")
                        .WithMany()
                        .HasForeignKey("UpdatePeopleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentType");

                    b.Navigation("Projects");

                    b.Navigation("UpdatePeople");
                });

            modelBuilder.Entity("ProjectManagement.Models.ProjectTypeDocumentAssociationTable", b =>
                {
                    b.HasOne("ProjectManagement.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("ProjectManagement.Models.Projects", b =>
                {
                    b.HasOne("ProjectCycleManage.Model.ProjFlowTable", "ProjInfor")
                        .WithMany()
                        .HasForeignKey("ProjInforId");

                    b.HasOne("ProjectManagement.Models.PeopleTable", "ProjectLeader")
                        .WithMany()
                        .HasForeignKey("ProjectLeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectManagement.Models.ProjectPhaseStatus", "ProjectPhaseStatus")
                        .WithMany()
                        .HasForeignKey("ProjectPhaseStatusId");

                    b.HasOne("ProjectManagement.Models.ProjectStage", "ProjectStage")
                        .WithMany()
                        .HasForeignKey("ProjectStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Models.EquipmentType", "equipmenttype")
                        .WithMany()
                        .HasForeignKey("equipmenttypeId");

                    b.HasOne("ProjectManagement.Models.PeopleTable", "projectfollowupperson")
                        .WithMany()
                        .HasForeignKey("projectfollowuppersonId");

                    b.HasOne("ProjectManagement.Models.TypeTable", "type")
                        .WithMany()
                        .HasForeignKey("typeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProjInfor");

                    b.Navigation("ProjectLeader");

                    b.Navigation("ProjectPhaseStatus");

                    b.Navigation("ProjectStage");

                    b.Navigation("equipmenttype");

                    b.Navigation("projectfollowupperson");

                    b.Navigation("type");
                });
#pragma warning restore 612, 618
        }
    }
}
