// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PomeloEntityFrameworkCoreTest.Data;

#nullable disable

namespace PomeloEntityFrameworkCoreTest.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.EquipmentType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipmentTypeId"));

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EquipmentTypeId");

                    b.ToTable("EquipmentType");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.InspectionRecord", b =>
                {
                    b.Property<int>("InspectionRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InspectionRecordId"));

                    b.Property<string>("CheckOpinion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CheckPeopleId")
                        .HasColumnType("int");

                    b.Property<string>("CheckResult")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CheckTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("InspectionRecordId");

                    b.HasIndex("CheckPeopleId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("InspectionRecord");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.PeopleTable", b =>
                {
                    b.Property<int>("PeopleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeopleId"));

                    b.Property<string>("PeopleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PeopleId");

                    b.ToTable("PeopleTable");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.ProjectDocumentStatus", b =>
                {
                    b.Property<int>("ProjectDocumentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectDocumentStatusId"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHasDocument")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TheLastUpDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatePeopleId")
                        .HasColumnType("int");

                    b.HasKey("ProjectDocumentStatusId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ProjectsId");

                    b.HasIndex("UpdatePeopleId");

                    b.ToTable("ProjectDocumentStatus");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.ProjectPhaseStatus", b =>
                {
                    b.Property<int>("ProjectPhaseStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectPhaseStatusId"));

                    b.Property<string>("ProjectPhaseStatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectPhaseStatusId");

                    b.ToTable("ProjectPhaseStatus");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.ProjectStage", b =>
                {
                    b.Property<int>("ProjectStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectStageId"));

                    b.Property<string>("ProjectStageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectStageId");

                    b.ToTable("ProjectStage");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.Projects", b =>
                {
                    b.Property<int>("ProjectsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectsId"));

                    b.Property<string>("ActualExpenditure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ProcurementMonth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectIdentifyingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectLeaderId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectPhaseStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectProgress")
                        .HasColumnType("int");

                    b.Property<int>("ProjectStageId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("equipmenttypeId")
                        .HasColumnType("int");

                    b.Property<int>("projectfollowuppersonId")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("typeId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsId");

                    b.HasIndex("ProjectLeaderId");

                    b.HasIndex("ProjectPhaseStatusId");

                    b.HasIndex("ProjectStageId");

                    b.HasIndex("equipmenttypeId");

                    b.HasIndex("projectfollowuppersonId");

                    b.HasIndex("typeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.TypeTable", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TypeId");

                    b.ToTable("TypeTable");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.InspectionRecord", b =>
                {
                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.PeopleTable", "CheckPeople")
                        .WithMany()
                        .HasForeignKey("CheckPeopleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.Projects", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckPeople");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.ProjectDocumentStatus", b =>
                {
                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.Projects", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.PeopleTable", "UpdatePeople")
                        .WithMany()
                        .HasForeignKey("UpdatePeopleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Projects");

                    b.Navigation("UpdatePeople");
                });

            modelBuilder.Entity("PomeloEntityFrameworkCoreTest.Models.Projects", b =>
                {
                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.PeopleTable", "ProjectLeader")
                        .WithMany()
                        .HasForeignKey("ProjectLeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.ProjectPhaseStatus", "ProjectPhaseStatus")
                        .WithMany()
                        .HasForeignKey("ProjectPhaseStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.ProjectStage", "ProjectStage")
                        .WithMany()
                        .HasForeignKey("ProjectStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.EquipmentType", "equipmenttype")
                        .WithMany()
                        .HasForeignKey("equipmenttypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.PeopleTable", "projectfollowupperson")
                        .WithMany()
                        .HasForeignKey("projectfollowuppersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PomeloEntityFrameworkCoreTest.Models.TypeTable", "type")
                        .WithMany()
                        .HasForeignKey("typeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectLeader");

                    b.Navigation("ProjectPhaseStatus");

                    b.Navigation("ProjectStage");

                    b.Navigation("equipmenttype");

                    b.Navigation("projectfollowupperson");

                    b.Navigation("type");
                });
#pragma warning restore 612, 618
        }
    }
}
